name: CD Workflow

on:
  push:
    branches:
      - master
  
jobs: 
  my-job-cd:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use SSH key
        run: 
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: 
          git config --global user.email "flaviobcn@gmail.com"
          git config --global user.name "salino3"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- -r https://github.com/salino3/auto-gh-pages-deploy.git
