
name: CD Workflow

on: 
  push:
    branches:
      - master
  
jobs: 
  my-job-cd:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy





